import type { CryptoEvent } from "../types";

const NOW = new Date();
const addDays = (n: number) => new Date(NOW.getTime() + n * 86400000).toISOString().slice(0, 10);

// Fixed 2026 dates
const D = (s: string) => `${s}T09:00:00.000Z`;

const baseSeed: Omit<CryptoEvent, "fetched_at">[] = [
  // ─── already-on-site, enriched ─────────────────────────────────────────────

  {
    id: "seed:token2049-singapore-2026",
    source: "manual",
    source_url: "https://www.token2049.com/",
    title: "TOKEN2049 Singapore 2026",
    summary: "Крупнейшая крипто-конференция мира — 20 000+ участников, 300+ спикеров, неделя side-ивентов.",
    description:
      "Token2049 — главный крипто-ивент в Азии. Доклады по глобальным Web3-трендам, институциональным потокам, инновациям. Hackathon, конкурс стартапов, нетворкинг, выставка. Инвесторы, CEO и топы индустрии со всего мира.",
    start_date: D("2026-10-07"),
    end_date: D("2026-10-08"),
    country: "Singapore",
    city: "Singapore",
    venue: "Marina Bay Sands",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "asia", "flagship", "web3"],
    tokens: [],
    pricing: "$299 — $4 999",
    speakers: [
      { name: "CZ", role: "Founder, Binance", bio: "Основатель крупнейшей по объёму торгов крипто-биржи Binance." },
      { name: "Paolo Ardoino", role: "CEO, Tether", bio: "CEO Tether — крупнейшего стейблкоина по капитализации." },
      { name: "Donald Trump Jr.", role: "World Liberty Financial", bio: "Представляет World Liberty Financial, связанный с семьёй экс-президента США." },
      { name: "Top executives OKX", role: "OKX" },
    ],
    audience: "Биржи и площадки, институциональные инвесторы / фонды, разработчики Web3 & стартапы, маркетинг и бизнес-развитие, OTC / DeFi / RWA / NFT проекты",
    image_url: undefined,
  },

  {
    id: "seed:solana-breakpoint-2026",
    source: "manual",
    source_url: "https://solana.com/breakpoint",
    title: "Solana Breakpoint 2026",
    summary: "Ежегодная флагманская конференция Solana — keynotes, talks, demos, workshops, side events.",
    description:
      "Solana Breakpoint — ежегодная сходка всей экосистемы Solana. Анонсы по протоколу, глубокие сессии по Firedancer, mobile-направлению и SVM-роллапам.",
    start_date: D("2026-11-15"),
    end_date: D("2026-11-17"),
    country: "United Kingdom",
    city: "London",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["conference", "solana", "flagship"],
    tokens: ["SOL"],
    pricing: "Upcoming",
    speakers: [],
    audience: "Solana-разработчики, валидаторы, фаундеры на SVM",
    image_url: undefined,
  },

  // ─── PDF — крупные ─────────────────────────────────────────────────────────

  {
    id: "seed:digital-assets-forum-london-2026",
    source: "manual",
    source_url: "https://eblockchainconvention.com/agenda-daf-london/",
    title: "Digital Assets Forum London 2026",
    summary: "Институциональный форум по цифровым активам: asset managers, банки, family offices, custody, регулирование.",
    description:
      "Повестка ориентирована на институциональную аудиторию. Темы: регулирование, custody, risk-management, DeFi для институционалов, токенизация активов и стратегии альфа. Представители фондов, банков и регуляторов.",
    start_date: D("2026-02-05"),
    end_date: D("2026-02-06"),
    country: "United Kingdom",
    city: "London",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["conference", "institutional", "regulation", "custody"],
    tokens: [],
    pricing: "~$1 340 / $2 011 / $6 707",
    speakers: [{ name: "Представители фондов, банков и регуляторов", role: "Список уточняется" }],
    audience: "Те, кто ищет институциональные партнёрства и размещение продуктов: asset managers, банки, family offices",
    image_url: undefined,
  },

  {
    id: "seed:ethcc-cannes-2026",
    source: "manual",
    source_url: "https://ethcc.io/",
    title: "EthCC Cannes 2026",
    summary: "Ключевая конференция Ethereum-сообщества: ядро L2, смарт-контракты, инфраструктура, приватность.",
    description:
      "Треки по ядру Ethereum и L2, разработке смарт-контрактов, инфраструктуре, приватности. Исследовательские доклады, воркшопы и community-сессии. Преимущественно разработчики и исследователи Ethereum, core-contributors, основатели инфраструктурных проектов.",
    start_date: D("2026-03-30"),
    end_date: D("2026-04-02"),
    country: "France",
    city: "Cannes",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "ethereum", "l2", "research"],
    tokens: ["ETH"],
    pricing: "€500 / €1 030 / €1 500 или €125 за один день",
    speakers: [{ name: "Ethereum core-contributors, исследователи экосистемы", role: "Список уточняется" }],
    audience: "Разработчики, R&D, стартапы и технические специалисты",
    image_url: undefined,
  },

  {
    id: "seed:paris-blockchain-week-2026",
    source: "manual",
    source_url: "https://www.parisblockchainweek.com/",
    title: "Paris Blockchain Week 2026",
    summary: "Флагманский European крипто-ивент: институциональные панели, RWA, DeFi, B2B-встречи, закрытые инвестиционные ланчи.",
    description:
      "Институциональные панели, регуляторы, RWA (real-world assets), инвестиции, NFT, DeFi, B2B-встречи, закрытые инвестиционные ланчи. Смешанный состав — от регуляторов и банков до основателей проектов и инвесторов; сильный блок по институциональной адаптации Web3.",
    start_date: D("2026-04-15"),
    end_date: D("2026-04-16"),
    country: "France",
    city: "Paris",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "institutional", "rwa", "defi", "nft"],
    tokens: [],
    pricing:
      "PRO €1 199 (некст €1 649) · VIP INVESTOR €2 299 (некст €2 999) · VIP MAX €3 699 (некст €4 999)\n\nPRO: все сцены, воркшопы, выставка, стартап-питчи, networking-app, вечеринка PBW.\nVIP INVESTOR: +VIP lounge, 100+ стартап deck, инвесторский завтрак.\nVIP MAX: +Royal Dinner (закрытый ужин), камерный круг институционалов.",
    speakers: [{ name: "Регуляторы, банкиры, фаундеры, VCs", role: "Список уточняется" }],
    audience: "Руководство, инвесторы, маркетинг и регуляторы",
    image_url: undefined,
  },

  {
    id: "seed:token2049-dubai-2026",
    source: "manual",
    source_url: "https://www.token2049.com/dubai",
    title: "TOKEN2049 Dubai 2026",
    summary: "Флагманский крипто-ивент в Дубае: регулирование, стейблкоины, custody, институциональный трейдинг.",
    description:
      "Ключевые доклады и панельные дискуссии по регулированию, стейблкоинам, биржевой инфраструктуре, custody, институциональному трейдингу. Отдельные треки для стартапов и NFT/Web3. Хорош для бизнес-нетворкинга и переговоров с exchange/инвесторами.",
    start_date: D("2026-04-29"),
    end_date: D("2026-04-30"),
    country: "United Arab Emirates",
    city: "Dubai",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "dubai", "regulation", "stablecoins", "institutional"],
    tokens: [],
    pricing: "$699 / $1 499 / $5 999",
    speakers: [
      { name: "Paolo Ardoino", role: "CEO, Tether" },
      { name: "Руководители бирж и венчуров", role: "Список уточняется" },
    ],
    audience: "Бизнес-нетворкинг, биржи, инвесторы, команды с легальным запуском в ЕС",
    image_url: undefined,
  },

  {
    id: "seed:nordic-blockchain-conference-2026",
    source: "manual",
    source_url: "https://nordicblockchain.com/",
    title: "Nordic Blockchain Conference 2026",
    summary: "Европейская конференция: блокчейн-инновации, MiCA, DeFi, токенизация, custody-решения.",
    description:
      "Три основные темы: (1) инновации в блокчейн-протоколах, связь с AI, DeSci, приватность и безопасность; (2) комплаенс, регулирование (MiCA и др.), налоговые и анти-фрод стратегии; (3) цифровые активы, токенизация, DeFi, институциональные финансовые продукты и custody-решения. Side-events: встречи по DeSci, панельные дискуссии, мастер-майнды, нетворкинг.",
    start_date: D("2026-05-26"),
    end_date: D("2026-05-27"),
    country: "Sweden",
    city: "Stockholm",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["conference", "europe", "mica", "defi", "custody"],
    tokens: [],
    pricing: "€240 (General) / €440 (Premium)",
    speakers: [
      { name: "Stellar, Safello", role: "Blockchain инфраструктура" },
      { name: "eToro, Bitcoin Suisse", role: "Биржи и финансовые сервисы" },
    ],
    audience: "Биржам, финтех-компаниям и инфраструктурным провайдерам с фокусом на европейское регулирование (MiCA, AML, custody)",
    image_url: undefined,
  },

  {
    id: "seed:crypto-valley-conference-2026",
    source: "manual",
    source_url: "https://www.cryptovalleyconference.com/",
    title: "The Crypto Valley Conference 2026",
    summary: "Двухдневные дискуссии о будущем блокчейна: технологии, экономика, право. 40+ докладов, вечеринка на катере по озеру Цуг.",
    description:
      "2-дневные углублённые дискуссии о текущем состоянии и будущем блокчейна. Мастер-классы. Более 40 презентаций от мировых лидеров отрасли. Темы: технологии, экономика, финансы, правовые и нормативные акты. Участники: стартапы, корпорации, академические круги, государственные структуры. Вечеринка на катере по озеру Цуг.",
    start_date: D("2026-05-28"),
    end_date: D("2026-05-29"),
    country: "Switzerland",
    city: "Rotkreuz",
    venue: "Rotkreuz",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["conference", "switzerland", "regulation"],
    tokens: [],
    pricing: "Уточняется",
    speakers: [{ name: "Лидеры блокчейн-протоколов, инфраструктурных провайдеров, финансовых институтов и регуляторов", role: "Список уточняется" }],
    audience: "Стартапы, корпорации, академические круги, государственные структуры",
    image_url: undefined,
  },

  {
    id: "seed:european-blockchain-convention-2026",
    source: "manual",
    source_url: "https://eblockchainconvention.com/",
    title: "European Blockchain Convention 2026",
    summary: "3 сцены: инфраструктура, DeFi, токенизация активов, регуляторика. LP-breakfast, раундтейблы, стартап-баттл.",
    description:
      "3 сцены: панели и keynotes по инфраструктуре, DeFi, токенизации активов и регуляторике. В программе: LP-breakfast, закрытые раундтейблы, стартап-баттл, side-events с фондами и биржами. Представители бирж, кастодианов и инфраструктуры (OKX, KuCoin, ByBit, Coinbase Institutional, Fireblocks и др.).",
    start_date: D("2026-09-16"),
    end_date: D("2026-09-17"),
    country: "Spain",
    city: "Barcelona",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["conference", "europe", "defi", "tokenization"],
    tokens: [],
    pricing: "€500 / €800 / €2 499",
    speakers: [
      { name: "OKX, KuCoin, ByBit", role: "Биржи" },
      { name: "Coinbase Institutional, Fireblocks", role: "Custody & инфраструктура" },
    ],
    audience: "Биржам/обменникам: листинг, ликвидность, институциональные клиенты. Инвесторам/фондам: LP-встречи, венчур. Разработчикам/Web3-проектам: стартап-битвы, dev-треки.",
    image_url: undefined,
  },

  {
    id: "seed:web-summit-2026",
    source: "manual",
    source_url: "https://websummit.com/",
    title: "Web Summit 2026",
    summary: "Крупнейшая мировая tech-конференция: AI, финтех, Web3/крипто, стартапы, инвесторы, Fortune 500.",
    description:
      "Главные спичи по глобальным технологическим трендам (AI, финтех, SaaS, Web3/крипто). Параллельные треки: стартапы, маркетинг, инвестиции, устойчивые технологии, регуляция. Вечерние нетворкинг-площадки и тематические встречи (AI, Web3, blockchain, data). Спикеры: Leaders Fortune 500, топ-стартаперы, инвесторы, государственные лидеры.",
    start_date: D("2026-11-09"),
    end_date: D("2026-11-12"),
    country: "Portugal",
    city: "Lisbon",
    venue: "Altice Arena",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "tech", "web3", "ai", "startup"],
    tokens: [],
    pricing:
      "Основной €950 (доступ к выставке, всем выступлениям, Night Summit, meetups).\nStandard Investor — бесплатно после одобрения.\nPlatinum Investor ~€1 950 (Investor Lounge, fast track, закрытые мероприятия).",
    speakers: [{ name: "Leaders Fortune 500, топ-стартаперы, инвесторы, государственные лидеры", role: "Список уточняется" }],
    audience: "Крупным биржам / экосистемам: бренд-экспозиция, встреча с регуляторами и Big Tech. Web3-стартапам / маркетингу.",
    image_url: undefined,
  },

  {
    id: "seed:blockchain-life-2026",
    source: "manual",
    source_url: "https://blockchain.life/",
    title: "Blockchain Life 2026",
    summary: "Top Web3 & крипто-ивент в Дубае в декабре: биржи, майнинг, DeFi, стартапы.",
    description: "Крупная Web3/крипто-конференция, завершающая год. Программа и спикеры уточняются.",
    start_date: D("2026-12-01"),
    end_date: D("2026-12-02"),
    country: "United Arab Emirates",
    city: "Dubai",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["conference", "dubai", "web3"],
    tokens: [],
    pricing: "$189 / $329 / $999",
    speakers: [],
    audience: "Web3-проекты, биржи, майнеры, инвесторы",
    image_url: undefined,
  },

  // ─── PDF — нишевые ─────────────────────────────────────────────────────────

  {
    id: "seed:pragma-cannes-2026",
    source: "manual",
    source_url: "https://ethglobal.com/events/pragma-cannes",
    title: "Pragma Cannes 2026 (ETHGlobal)",
    summary: "Однодневный саммит ETHGlobal: стейблкоины, L2, DeFi, кошельки, масштабирование, founders и bilders Web3.",
    description:
      "Pragma Cannes — однодневный саммит от ETHGlobal для дискуссий между разработчиками, основателями и лидерами мнений в экосистеме Ethereum и Web3. Темы: стейблкоины, решения второго уровня, DeFi, кошельки, масштабирование и совместимость.",
    start_date: D("2026-04-02"),
    end_date: D("2026-04-02"),
    country: "France",
    city: "Cannes",
    venue: "TBA",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["summit", "ethereum", "ethglobal", "defi", "l2"],
    tokens: ["ETH"],
    pricing:
      "Network Pass $29 · Hacker $49 · General $99 · ETHGlobal Plus $828 (все Pragma-ивенты на год + 100+ global side events + eSIMs + скидки на отели)",
    speakers: [
      { name: "Stani Kulechov", role: "CEO & Founder, Aave", bio: "Основатель крупнейшего DeFi-лендинг-протокола Aave." },
      { name: "Charles Guillemet", role: "CTO, Ledger", bio: "Технический директор Ledger." },
      { name: "Johann Eid", role: "Chief Business Officer, Chainlink" },
      { name: "Misha Putiatin", role: "Сооснователь, Symbiotic" },
    ],
    audience: "Разработчики, основатели и лидеры мнений в экосистеме Ethereum и Web3",
    image_url: undefined,
  },

  {
    id: "seed:vi3nna-congress-2026",
    source: "manual",
    source_url: "https://vi3nna.com/apply-to-attend",
    title: "VI3NNA Congress 2026",
    summary: "Элитный закрытый конгресс: политика, инновации и институциональный капитал в Web3, AI и цифровой экономике Европы.",
    description:
      "VI3NNA Congress — элитный двухдневный конгресс на пересечении политики, инноваций и институционального капитала в сфере Web3, AI и цифровой экономики Европы. Темы: регулирование, безопасность, хранение, токенизация активов, взаимодействие TradFi и DeFi. Ключевой итог — «Vienna Declaration»: ежегодный документ с приоритетами цифровой трансформации Европы. Мероприятие закрытое — нужно заполнить заявку.",
    start_date: D("2026-05-19"),
    end_date: D("2026-05-20"),
    country: "Austria",
    city: "Vienna",
    venue: "Vienna",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["congress", "policy", "institutional", "europe", "invite-only"],
    tokens: [],
    pricing: "По заявке (закрытое мероприятие): vi3nna.com/apply-to-attend",
    speakers: [
      { name: "Stephan Lutz", role: "CEO, BitMEX", bio: "Одна из пионерских крипто-деривативных бирж мира. Институциональный CEX-взгляд на регулирование и рынки." },
      { name: "Ruben Bombardi", role: "Главный регулятор криптоактивов Дубая", bio: "Ключевая фигура для понимания MENA-регуляторики." },
      { name: "Holger Neuhaus", role: "Head of Division, ЕЦБ (Frankfurt)", bio: "Отвечает за цифровые платежи и CBDC (цифровой евро) на уровне ЕЦБ." },
      { name: "Peter Kerstens", role: "Advisor & Ex-Counselor, Европейская комиссия", bio: "Один из архитекторов MiCA и цифровой финансовой политики ЕС." },
    ],
    audience: "Регуляторы, policy-специалисты, институциональный капитал, лидеры Web3-индустрии Европы",
    image_url: undefined,
  },

  {
    id: "seed:unblock-riga-2026",
    source: "manual",
    source_url: "https://unblock.events/",
    title: "un:block 2026",
    summary: "Крупнейшая конференция по блокчейну, финтеху и цифровым активам в Прибалтике: 2 500 участников, 100 спикеров, 40 стран.",
    description:
      "2 параллельные сцены: Business Stage (финансовые инновации, институциональное принятие крипто, регуляторика) и Legal Stage (MiCA, compliance, AML/KYC). Ключевые темы: MiCA, cross-border платежи, стейблкоины, blockchain в традиционном банкинге, Web3-инфраструктура, финтех в Балтийском и CEE-регионе, гейминг & NFT, supply chain.",
    start_date: D("2026-04-01"),
    end_date: D("2026-04-02"),
    country: "Latvia",
    city: "Riga",
    venue: "Riga",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["conference", "fintech", "mica", "compliance", "baltiq", "cee"],
    tokens: [],
    pricing: "Уточняется",
    speakers: [
      { name: "Alexander Rapatz", role: "CEO & Founding Partner, Black Manta Capital Partners", bio: "EU-ориентированный крипто-инвестор." },
      { name: "Dr. Julia Bond", role: "BD Director EU & UK, Sumsub" },
      { name: "Dejan Davidovic", role: "COO, Kriptomat", bio: "Крипто-биржа, ориентированная на Европу." },
      { name: "Viktor Bodnar", role: "BlockBen", bio: "Регулируемый крипто-банк в ЦВЕ." },
      { name: "Alexandra Lloyd", role: "Head of AML, YouHodler", bio: "Крипто-лендинг-платформа." },
      { name: "Sofian Berrahal", role: "CEO, Nexpay", bio: "Крипто-дружественный IBAN-провайдер." },
    ],
    audience: "Биржи, финтех-компании, compliance/AML специалисты, Web3-проекты в Европе и CEE",
    image_url: undefined,
  },

  {
    id: "seed:dutch-blockchain-week-2026",
    source: "manual",
    source_url: "https://dutchblockchainweek.com/",
    title: "Dutch Blockchain Week 2026",
    summary: "Неделя блокчейна в Амстердаме: панельные дискуссии, Web3-аналитика, нетворкинг, Dutch Blockchain Summit.",
    description:
      "Два полных дня, посвящённых анализу Web3, панельным дискуссиям, углублённым обсуждениям и нетворкингу для организаций, основателей, политиков и профессионалов, формирующих будущее цифровых активов. Включает Dutch Blockchain Summit и Litecoin Summit.",
    start_date: D("2026-06-22"),
    end_date: D("2026-06-28"),
    country: "Netherlands",
    city: "Amsterdam",
    venue: "Johan Cruijff ArenA",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "europe", "web3", "blockchain-week"],
    tokens: ["LTC"],
    pricing: "Уточняется (Litecoin Summit €84; DBS — отдельный билет)",
    speakers: [
      { name: "Brian Gahan", role: "General Manager Europe, Kraken" },
      { name: "Raoul Schipper", role: "Head of Strategic Accounts, Chainlink" },
      { name: "Amor Sexton", role: "COO, Blockdaemon" },
      { name: "Charlie Lee", role: "Director, Litecoin Foundation" },
      { name: "Meyade Curfs", role: "Lead Sales Executive, Bybit EU" },
      { name: "Rens de Groot", role: "CCO, Zerohash Europe" },
      { name: "Frank van Zegveld", role: "Head of Sales, Talos" },
    ],
    audience: "Организации, основатели, политики и профессионалы, формирующие будущее цифровых активов",
    image_url: undefined,
  },

  // ─── нишевые ───────────────────────────────────────────────────────────────

  {
    id: "seed:emea-stablecon-2026",
    source: "manual",
    source_url: "https://stablecon.com/",
    title: "EMEA Stablecon 2026",
    summary: "Профильный саммит по стейблкоинам в Европе: 1 500+ участников, 750+ C-Suite, 100+ спикеров.",
    description:
      "Крупнейший стейблкоин-саммит в EMEA-регионе. Ожидаемый масштаб: 1 500+ участников, 750+ C-Suite лидеров, 100+ спикеров. Фокус на институциональной инфраструктуре стейблкоинов, межсетевом взаимодействии и регуляции.",
    start_date: D("2026-05-19"),
    end_date: D("2026-05-20"),
    country: "Netherlands",
    city: "Amsterdam",
    venue: "Amsterdam",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["summit", "stablecoins", "emea", "institutional"],
    tokens: [],
    pricing: "Регистрация требуется",
    speakers: [
      { name: "Keith Grose", role: "CEO, Coinbase UK (CB Payments Ltd)" },
      { name: "Ivar Wiersma", role: "Head of EMEA, LayerZero", bio: "LayerZero — ключевой протокол межсетевого взаимодействия." },
      { name: "Brett Reeves", role: "Head of Europe, BitGo", bio: "BitGo — один из ведущих институциональных кастодианов." },
      { name: "Max von Wallenberg", role: "CEO, Iron (by MoonPay)", bio: "Крупнейший крипто-onramp в мире." },
      { name: "Chris Maurice", role: "Co-Founder & CEO, Yellow Card", bio: "Крупнейшая крипто-биржа в Африке." },
    ],
    audience: "Институциональные участники рынка стейблкоинов, C-Suite лидеры, протоколы межсетевого взаимодействия",
    image_url: undefined,
  },

  {
    id: "seed:bitcoin-plus-plus-vienna-2026",
    source: "manual",
    source_url: "https://btcpp.dev/",
    title: "bitcoin++ Vienna 2026 (economics edition)",
    summary: "Конференция разработчиков Bitcoin open-source, учёных и protocol developers — economics edition.",
    description:
      "Примут участие разработчики открытого ПО, учёные и разработчики протоколов со всего мира. Фокус на экономике Bitcoin, протоколе и смежных темах. Включает мастер-классы, обед и подарочный набор.",
    start_date: D("2026-05-27"),
    end_date: D("2026-05-28"),
    country: "Austria",
    city: "Vienna",
    venue: "Weitsicht Cobenzel",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["conference", "bitcoin", "developers", "open-source"],
    tokens: ["BTC"],
    pricing: "€288 (при оплате Bitcoin) / €320 (фиат) — пропуск на все конференции, мастер-классы, обед, подарочный набор",
    speakers: [{ name: "Open-source разработчики, учёные и protocol developers", role: "Список уточняется" }],
    audience: "Bitcoin-разработчики, исследователи, protocol developers",
    image_url: undefined,
  },

  {
    id: "seed:monerokon-2026",
    source: "manual",
    source_url: "https://monerokon.org/",
    title: "MoneroKon 2026",
    summary: "Конференция сообщества Monero: privacy-методы, ZK-криптография, права человека, децентрализация.",
    description:
      "Privacy-методы, ZK-криптография, права человека и блокчейн, регулирование, децентрализация. Конференция для участников экосистемы Monero и privacy-крипты.",
    start_date: D("2026-06-05"),
    end_date: D("2026-06-07"),
    country: "Poland",
    city: "Warsaw",
    venue: "Warsaw",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["conference", "monero", "privacy", "zk"],
    tokens: [],
    pricing: "€120",
    speakers: [],
    audience: "Monero-сообщество, privacy-исследователи, криптографы",
    image_url: undefined,
  },

  {
    id: "seed:btc-prague-2026",
    source: "manual",
    source_url: "https://www.btcprague.com/",
    title: "BTC Prague 2026",
    summary: "Крупнейшая European Bitcoin-конференция: разработка, майнинг, custody, торговля, законодательство.",
    description:
      "Фокус исключительно на Bitcoin: разработка, майнинг, custodial-решения, торговля, законодательство. Крупная выставка и B2C/B2B зоны. Известные Bitcoin-инфлюенсеры, разработчики биткоин-проекта, лидеры индустрии инфраструктуры и майнинга.",
    start_date: D("2026-06-11"),
    end_date: D("2026-06-13"),
    country: "Czech Republic",
    city: "Prague",
    venue: "Prague",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["conference", "bitcoin", "mining", "custody"],
    tokens: ["BTC"],
    pricing: "€63.5 / €286 / €345 / €1 737",
    speakers: [{ name: "Bitcoin-инфлюенсеры, разработчики биткоин-проекта, лидеры майнинга", role: "Список уточняется" }],
    audience: "Bitcoin-биржам и брокерам. Майнерам и хостинг-провайдерам. Разработчикам Bitcoin / Lightning. Инвесторам и макро-аналитикам.",
    image_url: undefined,
  },

  {
    id: "seed:ctrlshift-naples-2026",
    source: "manual",
    source_url: "https://www.ctrlshift.events/",
    title: "ctrl/shift 2026",
    summary: "Ethereum-конференция + хакатон в Неаполе. VIP-опция — вечеринка на яхте у Амальфитанского побережья.",
    description:
      "3-дневная Ethereum-конференция и хакатон. VIP-вариант включает путешествие на судне 16 июня (маршрут Капри и Амальфитанское побережье). На борту — основатели, разработчики, исследователи, специалисты по квантовой механике, AI и Web3.",
    start_date: D("2026-06-13"),
    end_date: D("2026-06-15"),
    country: "Italy",
    city: "Naples",
    venue: "Naples",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["conference", "ethereum", "hackathon"],
    tokens: ["ETH"],
    pricing: "€20 (ранний билет, 3 дня, еда и напитки) / €125 (VIP + вечеринка на яхте)",
    speakers: [
      { name: "Antonio Sanso", role: "Ethereum Foundation" },
    ],
    audience: "Ethereum-разработчики, исследователи, хакеры Web3",
    image_url: undefined,
  },

  {
    id: "seed:litecoin-summit-amsterdam-2026",
    source: "manual",
    source_url: "https://litecoin.org/",
    title: "Litecoin Summit 2026",
    summary: "Ежегодный саммит экосистемы Litecoin в Амстердаме: доклады, панели, воркшопы, нетворкинг.",
    description:
      "2 дня Litecoin Summit — все выступления и панельные дискуссии, мастер-классы и комнаты для обсуждений, выставочная площадка и зона для нетворкинга, напитки и кофе.",
    start_date: D("2026-06-22"),
    end_date: D("2026-06-23"),
    country: "Netherlands",
    city: "Amsterdam",
    venue: "Amsterdam",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["summit", "litecoin"],
    tokens: ["LTC"],
    pricing: "€84 (Litecoin Summit) / €200 (Litecoin Summit + Dutch Blockchain Summit)",
    speakers: [{ name: "Charlie Lee", role: "Director, Litecoin Foundation" }],
    audience: "Litecoin-сообщество, разработчики, держатели LTC",
    image_url: undefined,
  },

  // ─── оригинальные seed-ивенты (non-PDF) ───────────────────────────────────

  {
    id: "seed:ethdenver-2026",
    source: "manual",
    source_url: "https://www.ethdenver.com/",
    title: "ETHDenver 2026",
    summary: "Крупнейший и старейший Ethereum-ивент в мире: #BUIDLWeek, SporkDAO, хакатоны и неделя community-программы.",
    description:
      "ETHDenver собирает всю Ethereum-экосистему: многодневный хакатон, конференция и community-сходка. Сильный фокус на разработчиков — воркшопы, side-ивенты и баунти от L2, инфраструктурных и DeFi-протоколов.",
    start_date: D("2026-02-27"),
    end_date: D("2026-03-06"),
    country: "United States",
    city: "Denver",
    venue: "National Western Complex",
    is_online: false,
    language: "en",
    scale: "major",
    tags: ["conference", "hackathon", "ethereum", "flagship"],
    tokens: ["ETH"],
    pricing: "Бесплатно для BUIDLer'ов (трек разработчиков), $399 General, от $1 499 Sponsor",
    speakers: [
      { name: "John Paller", role: "Founder, ETHDenver", bio: "Основатель ETHDenver и Opolis." },
      { name: "Vitalik Buterin", role: "Co-founder, Ethereum" },
    ],
    audience: "Разработчики, билдеры, инженеры",
    image_url: undefined,
  },

  {
    id: "seed:london-defi-meetup",
    source: "manual",
    source_url: "https://www.meetup.com/london-defi/",
    title: "London DeFi Monthly Meetup",
    summary: "Ежемесячный митап лондонского DeFi-комьюнити: короткие доклады, нетворкинг и бесплатные напитки.",
    description: "Неформальная встреча с двумя короткими техническими докладами и нетворкингом после. Площадка — коворкинг в районе Шордич.",
    start_date: D(addDays(7)),
    end_date: D(addDays(7)),
    country: "United Kingdom",
    city: "London",
    venue: "Second Home Spitalfields",
    is_online: false,
    language: "en",
    scale: "local",
    tags: ["meetup", "defi", "local"],
    tokens: [],
    pricing: "Бесплатно",
    speakers: [],
    audience: "DeFi-пользователи, команды протоколов",
    image_url: undefined,
  },

  {
    id: "seed:bitcoin-policy-summit",
    source: "manual",
    source_url: "https://www.btcpolicy.org/summit",
    title: "Bitcoin Policy Summit DC",
    summary: "Закрытый саммит для регуляторов, законодателей и лидеров биткоин-индустрии в Вашингтоне.",
    description:
      "Ежегодная сходка у Капитолия США, посвящённая политике, регуляции и self-custody вокруг биткоина. Закрытые сессии по приглашениям плюс открытый keynote-день.",
    start_date: D(addDays(30)),
    end_date: D(addDays(31)),
    country: "United States",
    city: "Washington",
    venue: "US Capitol Visitor Center",
    is_online: false,
    language: "en",
    scale: "niche",
    tags: ["policy", "bitcoin", "regulation"],
    tokens: ["BTC"],
    pricing: "По приглашениям (индустрия); $499 — открытый день",
    speakers: [
      { name: "Senator Cynthia Lummis", role: "Сенатор США (R-WY)" },
      { name: "Jameson Lopp", role: "Со-основатель Casa" },
    ],
    audience: "Compliance, юристы, policy-специалисты",
    image_url: undefined,
  },

  {
    id: "seed:online-zk-workshop",
    source: "manual",
    source_url: "https://0xparc.org/",
    title: "Intro to ZK Circuits — Online Workshop",
    summary: "Практическое введение в построение zero-knowledge схем на Circom и Noir.",
    description:
      "Двухдневный онлайн-воркшоп: основы ZK, сборка простой схемы на Circom, портирование её на Noir. Понадобится ноутбук с установленным Node 20+.",
    start_date: D(addDays(14)),
    end_date: D(addDays(15)),
    country: undefined,
    city: undefined,
    venue: "Онлайн (Zoom)",
    is_online: true,
    language: "en",
    scale: "niche",
    tags: ["workshop", "zk", "online"],
    tokens: [],
    pricing: "Бесплатно для студентов, $99 General",
    speakers: [{ name: "Команда 0xPARC", role: "Исследователи" }],
    audience: "Разработчики, билдеры, инженеры",
    image_url: undefined,
  },
];

export function getSeedEvents(): CryptoEvent[] {
  const fetched_at = new Date().toISOString();
  return baseSeed.map((e) => ({ ...e, fetched_at }));
}
